codemate-oj/codemate-core

- packages/hydrooj/src/service/layers/response.ts
- packages/hydrooj/src/service/server.ts
feat(core): deny no json header access
Deny request when a user without super admin accessing @hydrooj/ui-default pages.
> feat(core): deny no json header access

- .dockerignore
- .gitignore
- Dockerfile
- docker-compose.yml
- package.json
> chore: add docker

- Dockerfile
Sorry for the stupid bug.
~It works on my machine~
> fix: docker from node:20

- test/main.ts
> fix: 具有 codemate 特色的测试

- packages/codemate-plugin/package.json
- packages/codemate-plugin/plugins/sms-register/index.ts
- packages/codemate-plugin/plugins/sms-register/lib.ts
- packages/hydrooj/src/handler/user.ts
- packages/hydrooj/src/model/token.ts
- packages/hydrooj/src/model/user.ts
- packages/ui-default/templates/layout/mail.html
- packages/ui-default/templates/user_register_mail.html
> feat: register with sms code, email code

- packages/codemate-plugin/plugins/login-limit/index.ts
> feat: only allows one account to be logged in at one place

- packages/codemate-plugin/plugins/kv-service/index.ts
> feat: kv service

- packages/codemate-plugin/package.json
- packages/codemate-plugin/plugins/id-authentication/index.ts
- packages/codemate-plugin/plugins/id-authentication/lib.ts
> feat: IdVerify: use another api

- packages/codemate-plugin/plugins/assign-problem-list/index.ts
- packages/codemate-plugin/templates/system_plist_edit.html
- packages/codemate-plugin/templates/system_plist_main.html
- packages/hydrooj/src/error.ts
- packages/hydrooj/src/handler/contest.ts
- packages/hydrooj/src/handler/problem.ts
- packages/hydrooj/src/interface.ts
- packages/hydrooj/src/model/problem.ts
- packages/hydrooj/src/model/user.ts
- packages/ui-default/locales/zh.yaml
- packages/ui-default/templates/components/tree-renderer.html
- packages/ui-default/templates/contest_edit.html
- 比赛和实名相关
- 单题assign权限
- 系统题单管理
> feat: 迁移现有oj功能

- packages/codemate-plugin/plugins/login-limit/index.ts
> fix: add IP white list, local IPs are in the whitelist by default

- packages/codemate-plugin/plugins/ranking/index.ts
- packages/hydrooj/src/handler/domain.ts
- packages/hydrooj/src/script/rating.ts
see apifox for more info about this
> feat: rp, but with language

- packages/codemate-plugin/plugins/user-plist/index.ts
> feat: user-plist

- packages/hydrooj/src/interface.ts
- packages/hydrooj/src/model/problem.ts
- packages/hydrooj/src/upgrade.ts
Generate problem brief when add a new problem or edit a problem.
> feat: problem brief

- packages/hydrooj/src/handler/problem.ts
- packages/ui-default/templates/partials/problem_sidebar_normal.html
> feat: button for approving problems

- packages/hydrooj/src/service/monitor.ts
> fix: remove monitor

- packages/codemate-plugin/plugins/user-homework/model.ts
更改查看小组作业的完成情况的逻辑：始终获取对应题目的最新评测记录
> fix: latest Record

- packages/codemate-plugin/plugins/user-channel/index.ts
- packages/codemate-plugin/plugins/user-channel/model.ts
> feat: add user channel

- packages/hydrooj/src/handler/problem.ts
> feat: add defined tag filter

- packages/hydrooj/src/model/opcount.ts
> fix: occasional frequency misjudgment

- packages/codemate-plugin/plugins/lostpass/index.ts
- packages/codemate-plugin/plugins/sms-register/index.ts
- packages/ui-default/templates/layout/mail.html
- packages/ui-default/templates/user_register_mail.html
> fix: replaced by aioj

- packages/hydrooj/src/handler/problem.ts
- packages/ui-default/templates/partials/filter_status.html
- packages/ui-default/templates/problem_main.html
> feat: add hidden and approved filter

- packages/hydrooj/src/handler/problem.ts
- packages/ui-default/pages/problem_main.page.ts
- packages/ui-default/templates/problem_main.html
> feat: add batch approval operation
